//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterSalesAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SalesID { get; set; }
        public string SalesStatus { get; set; }
        public Nullable<double> SalesAmount { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
